# alembic/script.py.mako
"""Initial schema

Revision ID: 417c6829221c
Revises: 
Create Date: 2025-12-16 05:12:11.534814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417c6829221c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###