# alembic/script.py.mako
"""initial schema

Revision ID: 583a5fff36d9
Revises: 
Create Date: 2026-01-20 07:37:10.252067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583a5fff36d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('cardio', 'strength', 'mobility', 'core', 'flexibility', 'other', name='exercise_categories'), nullable=False),
    sa.Column('measurement_type', sa.Enum('reps', 'seconds', 'minutes', 'meters', 'calories', name='exercise_measurement_types'), nullable=False),
    sa.Column('media', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('exercise_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('files',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('owner_type', sa.Enum('user', 'gym', 'dietician', name='file_owner_types'), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.Enum('image', 'document', 'video', 'audio', name='file_types'), nullable=False),
    sa.Column('purpose', sa.Enum('profile_image', 'gym_photo', 'verification_document', 'certificate', 'chat_attachment', 'face_id', 'workout_media', 'announcement_media', 'other', name='file_purposes'), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('storage_provider', sa.Enum('cloudinary', 's3', 'local', name='storage_providers'), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('storage_url', sa.String(), nullable=False),
    sa.Column('associated_table', sa.String(), nullable=True),
    sa.Column('associated_record_id', sa.String(), nullable=True),
    sa.Column('is_temporary', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    # sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index('ix_files_associated', 'files', ['associated_table', 'associated_record_id'], unique=False)
    op.create_index('ix_files_owner', 'files', ['owner_type', 'owner_id'], unique=False)
    op.create_index('ix_files_temporary', 'files', ['is_temporary'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('info', 'alert', 'reminder', 'achievement', name='notification_types'), server_default='info', nullable=False),
    sa.Column('scope', sa.Enum('individual', 'group', 'all', name='notification_scopes'), server_default='individual', nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('subscription_tiers',
    sa.Column('tier_id', sa.String(), nullable=False),
    sa.Column('tier_name', sa.String(), nullable=False),
    sa.Column('tier_type', sa.Enum('user', 'gym', name='subscription_tier_types'), nullable=False),
    sa.Column('price_monthly', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('price_yearly', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tier_id'),
    sa.UniqueConstraint('tier_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('profile_file_id', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('gym_user', 'dietician', 'gym_owner', 'admin', name='user_roles'), server_default='gym_user', nullable=False),
    sa.Column('status', sa.Enum('active', 'limited', 'suspended', 'inactive', name='user_statuses'), server_default='active', nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('payment_provider_customer_id', sa.String(), nullable=True),
    sa.Column('current_subscription_tier_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_subscription_tier_id'], ['subscription_tiers.tier_id'], ondelete='SET NULL'),
    # sa.ForeignKeyConstraint(['profile_file_id'], ['files.file_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dieticians',
    sa.Column('dietician_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('specializations', sa.JSON(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'inactive', name='dietician_statuses'), server_default='active', nullable=False),
    sa.Column('profile_file_id', sa.String(), nullable=True),
    sa.Column('average_rating', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('total_ratings', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_file_id'], ['files.file_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dietician_id')
    )
    op.create_table('gyms',
    sa.Column('gym_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('facilities', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'suspended', 'closed', name='gym_statuses'), server_default='draft', nullable=False),
    sa.Column('subscription_tier', sa.Enum('basic', 'standard', 'premium', name='gym_subscription_tiers'), server_default='basic', nullable=False),
    sa.Column('average_rating', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('total_ratings', sa.Integer(), nullable=True),
    sa.Column('opening_hours', sa.JSON(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('gym_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('receiver_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('ix_messages_receiver', 'messages', ['receiver_id'], unique=False)
    op.create_index('ix_messages_sender', 'messages', ['sender_id'], unique=False)
    op.create_index('ix_messages_sender_receiver', 'messages', ['sender_id', 'receiver_id'], unique=False)
    op.create_table('notification_recipients',
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.Column('notification_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notification_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipient_id')
    )
    op.create_table('oauth_accounts',
    sa.Column('oauth_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('google', 'apple', 'facebook', 'other', name='oauth_providers'), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('profile_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('oauth_id'),
    sa.UniqueConstraint('provider_user_id')
    )
    op.create_table('otps',
    sa.Column('otp_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('purpose', sa.Enum('email_verification', 'password_reset', 'other', name='otp_purposes'), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('otp_id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('used_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('ratings',
    sa.Column('rating_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('target_type', sa.Enum('gym', 'dietician', name='rating_target_types'), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('visit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('would_recommend', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rating_id')
    )
    op.create_index('ix_ratings_target', 'ratings', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_ratings_user_target', 'ratings', ['user_id', 'target_type', 'target_id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tier_id', sa.String(), nullable=True),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('trialing', 'active', 'past_due', 'cancelled', name='subscription_statuses'), server_default='trialing', nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('current_period_start', sa.TIMESTAMP(), nullable=False),
    sa.Column('current_period_end', sa.TIMESTAMP(), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tier_id'], ['subscription_tiers.tier_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_index('ix_subscriptions_user_status', 'subscriptions', ['user_id', 'status'], unique=False)
    op.create_table('verification_applications',
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('applicant_type', sa.Enum('gym_owner', 'dietician', name='verification_applicant_types'), nullable=False),
    sa.Column('applicant_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'more_info_required', name='verification_statuses'), server_default='pending', nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('info_request', sa.Text(), nullable=True),
    sa.Column('info_requested_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('info_provided_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('announcements',
    sa.Column('announcement_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('target_type', sa.Enum('gym', 'platform', name='announcement_target_types'), server_default='gym', nullable=False),
    sa.Column('gym_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('audience', sa.Enum('all', 'members', 'staff', name='announcement_audience'), server_default='all', nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='announcement_statuses'), server_default='draft', nullable=False),
    sa.Column('publish_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.gym_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('announcement_id')
    )
    op.create_table('checkins',
    sa.Column('checkin_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('gym_id', sa.String(), nullable=True),
    sa.Column('qr_nonce', sa.String(), nullable=False),
    sa.Column('qr_issued_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('provisional', 'confirmed', 'rejected', 'expired', name='checkin_statuses'), server_default='provisional', nullable=False),
    sa.Column('confirmed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('face_score', sa.Float(), nullable=True),
    sa.Column('client_lat', sa.Float(), nullable=True),
    sa.Column('client_lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.gym_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checkin_id'),
    sa.UniqueConstraint('qr_nonce')
    )
    op.create_table('client_assignments',
    sa.Column('assignment_id', sa.String(), nullable=False),
    sa.Column('dietician_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'ended', 'paused', name='client_assignment_statuses'), server_default='active', nullable=False),
    sa.Column('assigned_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('ended_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dietician_id'], ['dieticians.dietician_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id'),
    sa.UniqueConstraint('dietician_id', 'user_id', name='uq_client_assignment')
    )
    op.create_table('dietician_documents',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('dietician_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.Enum('certification', 'id', 'education', 'other', name='dietician_document_types'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dietician_id'], ['dieticians.dietician_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('gym_documents',
    sa.Column('gym_document_id', sa.String(), nullable=False),
    sa.Column('gym_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.Enum('business_license', 'tax_id', 'proof_of_ownership', 'other', name='gym_document_types'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.gym_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gym_document_id')
    )
    op.create_table('gym_photos',
    sa.Column('gym_photo_id', sa.String(), nullable=False),
    sa.Column('gym_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.gym_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gym_photo_id')
    )
    op.create_table('gym_staff',
    sa.Column('staff_id', sa.String(), nullable=False),
    sa.Column('gym_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('assigned_classes', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='staff_statuses'), server_default='active', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.gym_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=True),
    sa.Column('gym_id', sa.String(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('fee', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'refunded', name='payment_statuses'), server_default='pending', nullable=False),
    sa.Column('payment_type', sa.Enum('subscription', 'checkin', 'product', 'other', name='payment_types'), server_default='subscription', nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_payment_id', sa.String(), nullable=True),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.gym_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.subscription_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index('ix_payments_gym_status', 'payments', ['gym_id', 'status'], unique=False)
    op.create_index('ix_payments_user_subscription_status', 'payments', ['user_id', 'subscription_id', 'status'], unique=False)
    op.create_table('user_favorite_gyms',
    sa.Column('favorite_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('gym_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.gym_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favorite_id'),
    sa.UniqueConstraint('user_id', 'gym_id', name='uq_user_favorite_gym')
    )
    op.create_table('verification_documents',
    sa.Column('verification_document_id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.Enum('business_license', 'id', 'certification', 'proof_of_ownership', 'gym_photos', 'other', name='verification_document_types'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['verification_applications.application_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('verification_document_id')
    )
    op.create_table('workout_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('gym_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='workout_session_statuses'), server_default='in_progress', nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.gym_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('announcement_reads',
    sa.Column('read_id', sa.String(), nullable=False),
    sa.Column('announcement_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('read_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.announcement_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('read_id'),
    sa.UniqueConstraint('announcement_id', 'user_id', name='uq_announcement_read_user')
    )
    op.create_table('payouts',
    sa.Column('payout_id', sa.String(), nullable=False),
    sa.Column('gym_id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='payout_statuses'), server_default='pending', nullable=False),
    sa.Column('scheduled_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('processed_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_payout_id', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.gym_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('payout_id')
    )
    op.create_table('session_exercises',
    sa.Column('session_exercise_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('target', sa.JSON(), nullable=True),
    sa.Column('performed', sa.JSON(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_exercise_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_exercises')
    op.drop_table('payouts')
    op.drop_table('announcement_reads')
    op.drop_table('workout_sessions')
    op.drop_table('verification_documents')
    op.drop_table('user_favorite_gyms')
    op.drop_index('ix_payments_user_subscription_status', table_name='payments')
    op.drop_index('ix_payments_gym_status', table_name='payments')
    op.drop_table('payments')
    op.drop_table('gym_staff')
    op.drop_table('gym_photos')
    op.drop_table('gym_documents')
    op.drop_table('dietician_documents')
    op.drop_table('client_assignments')
    op.drop_table('checkins')
    op.drop_table('announcements')
    op.drop_table('verification_applications')
    op.drop_index('ix_subscriptions_user_status', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('sessions')
    op.drop_index('ix_ratings_user_target', table_name='ratings')
    op.drop_index('ix_ratings_target', table_name='ratings')
    op.drop_table('ratings')
    op.drop_table('password_reset_tokens')
    op.drop_table('otps')
    op.drop_table('oauth_accounts')
    op.drop_table('notification_recipients')
    op.drop_index('ix_messages_sender_receiver', table_name='messages')
    op.drop_index('ix_messages_sender', table_name='messages')
    op.drop_index('ix_messages_receiver', table_name='messages')
    op.drop_table('messages')
    op.drop_table('gyms')
    op.drop_table('dieticians')
    op.drop_table('users')
    op.drop_table('subscription_tiers')
    op.drop_table('notifications')
    op.drop_index('ix_files_temporary', table_name='files')
    op.drop_index('ix_files_owner', table_name='files')
    op.drop_index('ix_files_associated', table_name='files')
    op.drop_table('files')
    op.drop_table('exercises')
    # ### end Alembic commands ###

    # ---- FIX CIRCULAR FOREIGN KEYS ----

    op.create_foreign_key(
        'fk_files_uploaded_by_users',
        source_table='files',
        referent_table='users',
        local_cols=['uploaded_by'],
        remote_cols=['user_id'],
        ondelete='SET NULL'
    )

    op.create_foreign_key(
        'fk_users_profile_file_files',
        source_table='users',
        referent_table='files',
        local_cols=['profile_file_id'],
        remote_cols=['file_id'],
        ondelete='SET NULL'
    )
